pull_requests:
  do_not_increment_build_number: true
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  nodejs_version: "Stable"
branches:
  except:
  - ci/travis
  - ci/wercker

init:
- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"

install:
- pip install codecov

build_script:
- ps: .\build.ps1 -Configuration Release -Target AppVeyor
- ps: codecov -f $(Get-ChildItem -Path "./" -Name "OpenCover.xml" -Recurse -File | select -First 1) -X gcov
- ps: |
    $wc = New-Object 'System.Net.WebClient'
    Get-ChildItem -Path "./" -Name "TestResult*.xml" -Recurse -File | % {
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $_))
    }

artifacts:
- path: artifacts\**\*.zip
- path: artifacts\**\*.nupkg

test: off

cache:
- tools -> .build/tools.cake,tools/packages.config
