image:
  - Ubuntu
  - macos
  - Visual Studio 2019
matrix:
  fast_finish: true
for:
-
  matrix:
    only:
      - image: macos
  environment:
    DOTNET_ROOT: "/Users/appveyor/.dotnet"
  install:
    - brew update
    - brew install mono
-
  matrix:
    except:
      - image: Visual Studio 2019
  skip_commits:
    files:
      - docs/*
  skip_tags: true

pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
environment:
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: "-t7z -m0=lzma -mx=9"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
branches:
  except:
    - ci/travis
    - ci/wercker
    - gh-pages
    - /dependabot\/.*/

init:
  - dotnet --info

build_script:
  - pwsh: ./build.ps1 --target=Tests

after_test:
  - pwsh: Remove-Item -Path "./tools" -Recurse -Include "*.nupkg","*.snupkg"

deploy_script:
  - pwsh: ./build.ps1 --target=Deployment

cache:
  - 'tools -> .build/addins.cake,.build/modules.cake,.build/tools.cake,build.config'
