image:
- Visual Studio 2017
- Ubuntu
matrix:
  fast_finish: true
for:
-
  matrix:
    only:
      - image: Ubuntu
  skip_commits:
    files:
      - docs/*
pull_requests:
  do_not_increment_build_number: true
environment:
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: "-t7z -m0=lzma -mx=9"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  nodejs_version: "10"
stack: node 10
branches:
  except:
  - ci/travis
  - ci/wercker
  - gh-pages
  - /dependabot\/.*/

install:
- ps: if ($isWindows) { Install-Product node $env:nodejs_version }
- npm update -g yarn
- node --version
- npm --version

build_script:
- ps: |
    if ($isWindows) {
      .\build.ps1 -Configuration Release -Target AppVeyor
    } else {
      .\build.ps1 -Configuration Release -Target AppVeyor-Linux
    }
- ps: |
    $wc = New-Object 'System.Net.WebClient'
    Get-ChildItem -Path "./" -Name "TestResult*.xml" -Recurse -File | % {
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $_))
    }

test: off

cache:
- tools -> build.ps1,setup.cake
- src/Localization.Demo/node_modules -> src/Localization.Demo/package.json
- src/Localization.Demo/wwwroot/lib -> src/Localization.Demo/package.json
