language: csharp

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - CONFIGURATION: Release

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      dotnet: 1.0.0-preview2-003121
      mono: 4.0.5
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: 4.0.5

branches:
  except:
    - ci/appveyor
    - ci/wercker

script:
  - bash build -r -b -c $CONFIGURATION
  - bash .build/prepareCoverage
  - bash build -t -c $CONFIGURATION
  - bash <(curl -s https://codecov.io/bash) -f test-results/coverageResults.txt
