language: csharp

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - CONFIGURATION: Release
os:
  - linux
  - osx
mono: 4.4.2
dotnet: 2.0.3
node_js: "lts/*"

branches:
  except:
    - ci/appveyor
    - ci/wercker
    - /^v[0-9]/ # Skip tag builds, these should already have been tested before the tag was created
    - gh-pages

before_install:
  - git fetch --unshallow

script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ulimit -n 1024; fi
  - chmod +x build.sh
  - ./build.sh

cache:
  bundler: true
  directories:
    - tools
    - src/Localization.Demo/node_modules
    - src/Localization.Demo/wwwroot/lib

before_cache:
  - rm -f tools/packages.config

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c330b5bf936d03eec002
