language: csharp
sudo: required

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - CONFIGURATION: Release

mono:
  - 4.0.5

dotnet:
  - 1.0.0-preview2-003121

os:
  - linux
  - osx

branches:
  except:
    - ci/appveyor
    - ci/wercker

script:
  - bash build -r -b -c $CONFIGURATION
  - bash .build/prepareCoverage
  - bash build -t -c $CONFIGURATION
  - bash <(curl -s https://codecov.io/bash)
