language: csharp
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - CONFIGURATION: Release

mono:
  - 4.0.5

dotnet:
  - 1.0.0-preview2-003131

os:
  - linux
  - osx

branches:
  except:
    - ci/appveyor
    - ci/wercker

script:
  - ./build -r -b -c $CONFIGURATION
  - ./.build/prepareCoverage
  - ./build -t -c $CONFIGURATION
  - bash <(curl -s https://codecov.io/bash)
