version: 1

update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
    - AdmiringWorm
    default_labels:
    - "dependencies"
    - ".NET"
    - "cla-not-needed"
  - package_manager: "javascript"
    directory: "/src/Localization.Demo"
    update_schedule: "live"
    default_reviewers:
    - AdmiringWorm
    default_labels:
    - "dependencies"
    - "javascript"
    - "cla-not-needed"
